# -*- coding: utf-8 -*-
"""Iris flower classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3nqjn5f2oYZcH9bxIdZcYuv4py0kY4R
"""

import pandas as pd

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

import seaborn as sns

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names=["sepal_length","sepal_width","petal_length","petal_width","class"]
iris_data=pd.read_csv(url,names=column_names)

iris_data.head(5)

type(iris_data)

iris_data.iloc[50:100]

iris_data.describe()

sns.pairplot(iris_data,hue="class")

X=iris_data.drop("class",axis=1)
x

y=iris_data["class"]
y

X_train , X_test , y_train , y_test=train_test_split(X,y,test_size=0.3,random_state=42)

X_train

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

y_pred=knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))

print(classification_report(y_test,y_pred))

X_test.head(2)

new_data=pd.DataFrame({"sepal_length":[5.1],"sepal_width":[3.5],"petal_length":1.4,"petal_width":0.2})

prediction=knn.predict(new_data)

prediction

new_data1=pd.DataFrame({"sepal_length":[6.7],"sepal_width":[6.5],"petal_length":3.4,"petal_width":2.9})

prediction=knn.predict(new_data1)

prediction[0]